### ISSUE TITLE
Unable to run listOSPolicyAssignments in Google Cloud Function

### ISSUE THREAD

**Issue by johndbro1** [googleapis/nodejs-os-config#173]
I'm trying to consume the listOSPolicyAssignments API, and I consistently get the following error:

`callListOSPolicyAssignments failure:  TypeError: Cannot read property 'apply' of undefined"`

I'm using the code from sample provided in this git project (nodejs-os-config).

I thought it might be a permissions issue, but I was able to get the listVulnerabilityReportsAsync sample to run.

**Comment by tmatsuo** [comment]
@johndbro1 Thanks for your report.
Can you provide a reproducible steps and files? It will help us understand the issue.

I briefly took a look at the documentation at:
https://cloud.google.com/compute/docs/os-configuration-management/manage-os-policy

It seems like `OSPolicyAssignment Viewer (roles/osconfig.osPolicyAssignmentViewer)` is required. Just in case, does your service account have this role? 

Thanks,

**Comment by johndbro1** [comment]
Thank you for looking at this for me.

I can confirm that my service account has the `OSPolicyAsignment Viewer`.  I've also confirmed that I can access the `listVulnerabilityReportAsync `method and it returns the correct data.  

I've attached my index.js and package.json (both as text files) for you.  

Steps to reproduce:

1. Create a cloud function using the provided javascript code and packaging. Change the name of the project as appropriate
2. execute the cloud function using the 'test' button

Expected results: a list of os-config policies for the specified project and zone
Actual results: `callListOSPolicyAssignments failure: TypeError: Cannot read property 'apply' of undefined"
`


[index.js.txt](https://github.com/googleapis/nodejs-os-config/files/7849648/index.js.txt)
[package.json.txt](https://github.com/googleapis/nodejs-os-config/files/7849650/package.json.txt)

**Comment by tmatsuo** [comment]
Thanks! I'll try to reproduce.

**Comment by sofisl** [comment]
I've successfully reproduced this issue, and reached out to the API team for further guidance.

**Comment by sofisl** [comment]
Update: it seems that this is a generator issue. I've reached out to @alexander-fenster for help.
